// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGFegdnYnSFl2ZQjkUlWRk8-3bVsbQ58',
    appId: '1:386819934763:web:221d1793bcc3d4a11fb86e',
    messagingSenderId: '386819934763',
    projectId: 'senddata-e87ec',
    authDomain: 'senddata-e87ec.firebaseapp.com',
    storageBucket: 'senddata-e87ec.appspot.com',
    measurementId: 'G-X4RXQWPBZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHqlULZq4ooV6THvxThLF9R8FYiOFpTj4',
    appId: '1:386819934763:android:7ef28cba2abfbf711fb86e',
    messagingSenderId: '386819934763',
    projectId: 'senddata-e87ec',
    storageBucket: 'senddata-e87ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfMRN5xrQ-lkzLvHTC4aPIJNKabzZUGy8',
    appId: '1:386819934763:ios:3448ce2c23bd7c8d1fb86e',
    messagingSenderId: '386819934763',
    projectId: 'senddata-e87ec',
    storageBucket: 'senddata-e87ec.appspot.com',
    iosBundleId: 'com.example.firebaseForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfMRN5xrQ-lkzLvHTC4aPIJNKabzZUGy8',
    appId: '1:386819934763:ios:2e1c803e8f8e10471fb86e',
    messagingSenderId: '386819934763',
    projectId: 'senddata-e87ec',
    storageBucket: 'senddata-e87ec.appspot.com',
    iosBundleId: 'com.example.firebaseForm.RunnerTests',
  );
}
